# Generated by Django 4.2.6 on 2023-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_footeraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footeraddress',
            options={'verbose_name_plural': 'Footer Address'},
        ),
        migrations.AddField(
            model_name='footeraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='footeraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='footeraddress',
            name='working_days',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
