# Generated by Django 4.2.6 on 2023-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_footeraddress_options_footeraddress_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('working_days', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
