# Generated by Django 4.2.6 on 2023-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
        migrations.DeleteModel(
            name='FooterAddress',
        ),
    ]
