# Generated by Django 4.2.6 on 2023-10-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_contactform_delete_footeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Asked Questions',
            },
        ),
    ]
