# Generated by Django 4.2.6 on 2023-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_profile_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='user_app/image/no_profile.jpg', upload_to='profile'),
        ),
    ]
